X=MsgBox("The computer needs to restart",0+16,"Error")
X=MsgBox("The computer needs to restart",0+16,"Error")
X=MsgBox("The computer needs to restart",0+16,"Error")
X=MsgBox("The computer needs to restart",0+16,"Error")
X=MsgBox("The computer needs to restart",0+16,"Error")
X=MsgBox("The computer needs to restart",0+16,"Error")
X=MsgBox("The computer needs to restart",0+16,"Error")
X=MsgBox("The computer needs to restart",0+16,"Error")
